#Triangle, pentagonal, and hexagonal numbers are generated by
#the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.




def checkNum(N):
    triNumList=[]
    pentNumList=[]
    hexNumList=[]
    i=1
    for i in range(1,N+1):
        triNumList.append((i*(i+1))//2)
        pentNumList.append((i*((3*i)-1))//2)
        hexNumList.append(i*((2*i)-1))
        i+=1
    matchesList=[]
    for i in triNumList:
        if i in pentNumList and i in hexNumList:
            matchesList.append(i)
    return matchesList
    
